### ISSUE TITLE
Data Not pulling through

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#73]
The Staging platform doesn't have any data pulling through
![image](https://github.com/kartoza/Woolpert/assets/139763251/67d68e08-adfa-4c9c-b286-6532b94e636a)

**Comment by NyakudyaA** [comment]
@BooyeWLP what username are you using so that we can test

**Comment by BooyeWLP** [comment]
The Woolpert_user username

**Comment by BooyeWLP** [comment]
good morning @NyakudyaA  have you had a chance to look at this as yet? I also checked the wapp_user and both the accouts doesn't seem to have access/permissions?

**Comment by EliVolsch** [comment]
@BooyeWLP We checked the account access for both accounts when we first noticed the issue. Both accounts have adequate access to the data. We believe the issue is with Geofencing. We are working to resolve this issue and will keep you updated in the process

**Comment by NyakudyaA** [comment]
@BooyeWLP This is resolved for the woolpert user. Besides having normal rights you should also have admin rights so that you can update permissions for the layers.

![image](https://github.com/kartoza/Woolpert/assets/2510900/2d618455-413d-4da1-9317-18af94d095a0)

Each time a new user is registered you have to grant them access to the layers

**Comment by EliVolsch** [comment]
@BooyeWLP Can you re-test this issue and inform us of the results

**Comment by BooyeWLP** [comment]
All of them are showing thank you, the only layer that still doesn't show data is the power plants

**Comment by BooyeWLP** [comment]
Also looks like I only have normal user rights at the moment:
![image](https://github.com/kartoza/Woolpert/assets/139763251/2c0c99a6-f73e-47a4-b078-f92063e17410)

**Comment by EliVolsch** [comment]
I upgraded the woolpert_user account to staff status which should give
admin rights to the account. If the permissions remain unchanged please
reach out and i will look at it again

**Comment by BooyeWLP** [comment]
Great looks like I have more rights now, will play around and let you know if I encounter any problems thanks

**Comment by EliVolsch** [comment]
@NyakudyaA it seems the power plants layer is still not loading. Permissions seem to be set correctly

![image](https://github.com/kartoza/Woolpert/assets/107027990/a6c8db29-ab16-4486-842e-0b26b3ef90ee)

**Comment by NyakudyaA** [comment]
@LunaAsefaw I know the powerplant layer has been changed it's name a couple of times. Can you confirm which one needs to visible

**Comment by LunaAsefaw** [comment]
@NyakudyaA 'powerplant' is the correct layer in the DB. I have removed the other layer from Geonode so the correct layer is displayed there

**Comment by NyakudyaA** [comment]
So can we close this?

**Comment by LunaAsefaw** [comment]
no because I can see the layer he is referring too so he is referencing the correct powerplant layer so his reason for failing to see the data could be a permission issue or something else but it's not because he is viewing the wrong layer
![image](https://github.com/kartoza/Woolpert/assets/90245715/1135f3c5-9f9f-4be0-ac15-170fefd1b061)

**Comment by NyakudyaA** [comment]
But I can see data in there 
![image](https://github.com/kartoza/Woolpert/assets/2510900/478f605e-f859-4ee7-aedb-7fe7d341eea1)

Can't you @LunaAsefaw

**Comment by EliVolsch** [comment]
With our admin profiles we don't have the same problems viewing the layers.
I encourage you to try and replicate this from the users perspective. In
this case login with the woolpert_user credentials when testing.

**Comment by NyakudyaA** [comment]
This is fixed
