### ISSUE TITLE
Feature attribute table not loading

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#88]
![image](https://github.com/kartoza/Woolpert/assets/139763251/5001631f-420e-4c68-b0e1-04dc1fc1c144)
It looks like this is the issue on all layers except for powerplants

Additionally on Powerlines, there is no popup when clicking on a line:
![image](https://github.com/kartoza/Woolpert/assets/139763251/fb7f3951-3426-40e3-a954-4b220419697f)

**Comment by NyakudyaA** [comment]
@BooyeWLP Did you perhaps change the layer definition in the DB, This will cause errors in GeoNode. If you made changes please let me know which layers have been modified so that I can update them.

The error you get is
```
'Failed to run GetFeatureInfo on layer geonode:powerline\nRendering process failed. Layers: geonode:powerline\njava.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: column "all_countries" does not exist\n  Position: 85\nERROR: column "all_countries" does not exist\n  Position: 85'
```

**Comment by BooyeWLP** [comment]
Thanks @NyakudyaA  there were a couple of changes that we made, I just sent the document to Luna, I'll forward to you as well if you weren't copied

**Comment by NyakudyaA** [comment]
@BooyeWLP This is fixed. Next time when the structure of the table changes you will need to let us know or we can document what needs to be done to reload the table structure

**Comment by NyakudyaA** [comment]
This is fixed

**Comment by BooyeWLP** [comment]
Thanks Admire, I can see the popups of the features now, however the attribute tables still don't want to load

**Comment by NyakudyaA** [comment]
How are you viewing the attribute table
![image](https://github.com/kartoza/Woolpert/assets/2510900/d564ff71-cee8-4662-8f06-99e4545f1dcc)

**Comment by BooyeWLP** [comment]
Hmmm I'm trying to open it from the datalist:

![image](https://github.com/kartoza/Woolpert/assets/139763251/b07f0285-0118-4b15-820b-2dda9117616f)


![image](https://github.com/kartoza/Woolpert/assets/139763251/f55a95b4-8c66-4cac-b2cf-9677933ce565)

**Comment by NyakudyaA** [comment]
I can access them, what user are you using? It might be a permission issue.

**Comment by BooyeWLP** [comment]
That's strange, I'm using woolpert_user

**Comment by NyakudyaA** [comment]
I will test with that user and see if it's a permission issue

**Comment by BooyeWLP** [comment]
Hi @NyakudyaA have you had any luck with this, I see we can still not see the attributes on a lot of layers (looks like we can only view powerplants)

**Comment by NyakudyaA** [comment]
Let me login and test with the user, will revert soon

**Comment by NyakudyaA** [comment]
@BooyeWLP This is a permission issue, I fixed this before and now it has reverted. Can we standardize what kind of permission you need here?

The issue was fixed here https://github.com/kartoza/Woolpert/issues/73

Can we agree on a proper permission matrix here?
![image](https://github.com/kartoza/Woolpert/assets/2510900/82681a82-6107-4b8c-8e59-44ba32b4861e)

I suggest we standardize and remove all the test groups and apply the following rules

* When a new user is registered on the system we need to add them to the ecowas group.
* All users are automatically added to the registered group. 

cc @EliVolsch
If they are any other permission issue please comment them here and we can fix this in one go

**Comment by EliVolsch** [comment]
@NyakudyaA I agree on adding all registered member to the ecowas group. We would need to have a discussion on permission matrix so we can fine tune which groups should be able to see what.

I have checked the layer using woolpert_user account and it seems like everything is working as expected. If any more permission issues pop up i will comment here. 
![image](https://github.com/kartoza/Woolpert/assets/107027990/47b11b80-a83b-4cc8-b4a3-1369ec103eb2)

**Comment by BooyeWLP** [comment]
Hi @NyakudyaA @EliVolsch , it looks like the WAPP members also didn't have access to view the attributes, however I changed it but now they have edit and download rights.

Is there a way to change the viewer roles to having access to viewing the attributes as well? - but not download or edit

**Comment by NyakudyaA** [comment]
Yes, I will look at it and adjust

**Comment by NyakudyaA** [comment]
This is fixed and working properly
![Peek 2023-09-18 12-44](https://github.com/kartoza/Woolpert/assets/2510900/d393a6ae-6024-4fb4-a422-4cc0d3b7d2bb)
